// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3DoQcEtAodPdlGXdSirNfsxSp70P8Ukg',
    appId: '1:348278272753:web:4605661f9da346840d6f50',
    messagingSenderId: '348278272753',
    projectId: 'study-flow-f9315',
    authDomain: 'study-flow-f9315.firebaseapp.com',
    storageBucket: 'study-flow-f9315.firebasestorage.app',
    measurementId: 'G-TGVNWLJJRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqv0IR1ohImhKkP0Mmg9wWKvoMUBibLO8',
    appId: '1:348278272753:android:44182c0ad9c44e5c0d6f50',
    messagingSenderId: '348278272753',
    projectId: 'study-flow-f9315',
    storageBucket: 'study-flow-f9315.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBa7HjDDD2IdfEDd0miboEKZNyfAvTm1Y',
    appId: '1:348278272753:ios:c6aafc45f78381c70d6f50',
    messagingSenderId: '348278272753',
    projectId: 'study-flow-f9315',
    storageBucket: 'study-flow-f9315.firebasestorage.app',
    iosBundleId: 'com.example.studyFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBa7HjDDD2IdfEDd0miboEKZNyfAvTm1Y',
    appId: '1:348278272753:ios:c6aafc45f78381c70d6f50',
    messagingSenderId: '348278272753',
    projectId: 'study-flow-f9315',
    storageBucket: 'study-flow-f9315.firebasestorage.app',
    iosBundleId: 'com.example.studyFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3DoQcEtAodPdlGXdSirNfsxSp70P8Ukg',
    appId: '1:348278272753:web:6da1beab40222f940d6f50',
    messagingSenderId: '348278272753',
    projectId: 'study-flow-f9315',
    authDomain: 'study-flow-f9315.firebaseapp.com',
    storageBucket: 'study-flow-f9315.firebasestorage.app',
    measurementId: 'G-5WVG4VXGNK',
  );
}
